### ISSUE TITLE
The Wild Hunt

### ISSUE THREAD

**Issue by Xunnamius** [Xunnamius/supreme.xunn.io#9]
Welcome to my WILD HUNT! Or to put it another way: there are some upstream bugs I'd like to squash / enhancements I'd like to implement, all over the course of the next year or so. And they are (in no particular order as of yet):

- [ ] https://github.com/usmannasir/cyberpanel/issues/1117
- [ ] https://github.com/usmannasir/cyberpanel/issues/1121
- [ ] https://github.com/usmannasir/cyberpanel/issues/1109
- [ ] https://github.com/usmannasir/cyberpanel/issues/1120
- [ ] https://github.com/usmannasir/cyberpanel/issues/1071 (see [this](https://github.com/Xunnamius/supreme.xunn.io/issues/3) too)
- [ ] https://github.com/usmannasir/cyberpanel/issues/1068
- [ ] https://github.com/usmannasir/cyberpanel/issues/1091
- [ ] https://github.com/usmannasir/cyberpanel/issues/1092
- [ ] https://github.com/usmannasir/cyberpanel/issues/1043
- [ ] https://github.com/usmannasir/cyberpanel/issues/1064
- [ ] https://github.com/usmannasir/cyberpanel/issues/1065
- [ ] https://github.com/usmannasir/cyberpanel/issues/1046
- [ ] https://github.com/usmannasir/cyberpanel/issues/1047
- [ ] https://github.com/usmannasir/cyberpanel/issues/1049 (maybe)
- [ ] https://github.com/usmannasir/cyberpanel/issues/1050 (maybe)
- [ ] https://github.com/usmannasir/cyberpanel/issues/1052
- [ ] https://github.com/usmannasir/cyberpanel/issues/1039 (**definitely this!**)
- [ ] https://github.com/usmannasir/cyberpanel/issues/1038 (fake news)
- [ ] https://github.com/usmannasir/cyberpanel/issues/1025 (interesting; maybe)
- [ ] https://github.com/usmannasir/cyberpanel/issues/1028 and https://github.com/usmannasir/cyberpanel/issues/840 (the latter describes a bug with deletion too) (honestly, [we should add confirmations to all CUD operations](https://github.com/Xunnamius/supreme.xunn.io/issues/8))
- [ ] https://github.com/usmannasir/cyberpanel/issues/1037
- [ ] https://github.com/usmannasir/cyberpanel/issues/999 (see [this](https://github.com/Xunnamius/supreme.xunn.io/issues/6) too)
- [ ] https://github.com/usmannasir/cyberpanel/issues/1005 (something like this, at least)
- [ ] https://github.com/usmannasir/cyberpanel/issues/987 (👀 )
- [ ] https://github.com/usmannasir/cyberpanel/issues/946 and https://github.com/usmannasir/cyberpanel/issues/551 (**definitely these**)
- [ ] https://github.com/usmannasir/cyberpanel/issues/933 (maybe)
- [ ] https://github.com/usmannasir/cyberpanel/issues/915 (someone else might've already fixed it!)
- [ ] https://github.com/usmannasir/cyberpanel/issues/858 (is this still necessary?)
- [ ] https://github.com/usmannasir/cyberpanel/issues/842
- [ ] https://github.com/usmannasir/cyberpanel/issues/838 (👀 )
- [ ] https://github.com/usmannasir/cyberpanel/issues/831 ([rustic](https://github.com/rustic-rs/rustic/blob/main/docs/comparison-restic.md), you say? it's not fully tested, but still interesting)
- [ ] https://github.com/usmannasir/cyberpanel/issues/794 (maybe)
- [ ] https://github.com/usmannasir/cyberpanel/issues/745 (👀 )
- [ ] https://github.com/usmannasir/cyberpanel/issues/600 (good ideas)
- [ ] https://github.com/usmannasir/cyberpanel/issues/548 (**definitely this**)
- [ ] https://github.com/usmannasir/cyberpanel/issues/539 (👀 )
- [ ] https://github.com/usmannasir/cyberpanel/issues/506 and https://github.com/usmannasir/cyberpanel/issues/468 (👀 )
- [ ] https://github.com/usmannasir/cyberpanel/issues/396 (good idea)
- [ ] https://github.com/usmannasir/cyberpanel/issues/383 (maybe)
- [ ] https://github.com/usmannasir/cyberpanel/issues/389 (fix doesn't seem too complex)
- [ ] https://github.com/usmannasir/cyberpanel/issues/325 (interesting; maybe)
- [ ] https://github.com/usmannasir/cyberpanel/issues/276 (seems like more low-hanging fruit)
- [ ] https://github.com/usmannasir/cyberpanel/issues/147 (👀 )
- [] Consider integrating anything from https://github.com/tbaldur/cyberpanel-mods that seems interesting or useful

**Comment by Lvl4Sword** [comment]
Have you started on any of these?

**Comment by Lvl4Sword** [comment]
I was hoping there wouldn't be duplication of effort.
Looked at [#842](https://github.com/usmannasir/cyberpanel/issues/842) and made
https://github.com/usmannasir/cyberpanel/pull/1155 earlier to get that completed.
If you're on Discord or Libera IRC, I'd love to coordinate with you to get some of these knocked out.

:-)

**Comment by Xunnamius** [comment]
Sounds good! I have a discord (username is also Xunnamius). I'm still exploring the code base, and tweaking this fork to integrate nginx reverse-proxy and cloudflare management tools, but my goal is to ensure any fixes relevant to upstream are mergeable/PR-compatible.

**Comment by master3395** [comment]
I think several of these have been fixed over time.
